### ISSUE TITLE
Jetson TX2 support

### ISSUE THREAD

**Issue by HilmiK** [pfnet-research/chainer-trt#3]
Will there be a jetson tx2 support, by making this repository compatible with tensorrt 4.0? 

I know that there will be jetpack module which will be declared for jetson tx2 and tensorrt 5.0 but for now I would like to continue with that.

**Comment by belltailjp** [comment]
Hi. Sorry for the late reply.
TensorRT 5 introduced some backward compatibility-breaking changes in its internal behavior (although they look quite similar), where chainer-trt relies on. So unfortunately we cannot provide a support for both trt 4 and 5.
